services:
  build:
    build: .
    volumes:
      - .:/hoopblob
      - build_cache:/hoopblob/build
    command: ["bash", "-c", "make -j$(nproc) LIBBUTANO=/opt/butano/butano PYTHON=python3"]

volumes:
  build_cache:
